# Generated by Django 3.0.5 on 2020-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200416_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='descpription',
            field=models.TextField(default='None image <django.db.models.fields.AutoField>'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
