# Generated by Django 3.0.5 on 2020-04-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200416_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='rproduct',
        ),
    ]
