# Generated by Django 3.0.3 on 2020-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200212_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'buyer'), (2, 'seller')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.ManyToManyField(to='profiles.Role'),
        ),
    ]
